// Package aider projects the keystone surface Aider expects:
// `CONVENTIONS.md` at the repo root plus an `.aider.conf.yml` that
// points Aider at the project's orientation files.
//
// Aider has no per-file rule auto-loader the way Claude Code or Cursor
// do — it reads a handful of "always-loaded" files declared in
// `.aider.conf.yml`. So the projection strategy is different from
// Claude Code's path-triggered shims: aider gets one consolidated
// conventions file (mirrors AGENTS.md content) plus a config that
// loads it on every session.
package aider

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// ConventionsRelPath is the file Aider loads as a project-wide
// instruction set.
const ConventionsRelPath = "CONVENTIONS.md"

// ConfigRelPath is Aider's per-project config; `read:` points at the
// files Aider keeps in context every session.
const ConfigRelPath = ".aider.conf.yml"

// ProjectionResult records what ProjectAider wrote.
type ProjectionResult struct {
	Wrote []string
}

// ProjectAider emits CONVENTIONS.md (always-loaded content for Aider)
// and .aider.conf.yml (config telling Aider what to keep in context).
// content is typically the same body AGENTS.md uses — the agnostic
// adapter's DefaultBody().
func ProjectAider(projectDir, content string) (ProjectionResult, error) {
	var out ProjectionResult

	conv := filepath.Join(projectDir, ConventionsRelPath)
	body := ensureTrailingNewline([]byte(content))
	prev, _ := os.ReadFile(conv)
	if !bytes.Equal(prev, body) {
		if err := atomicWrite(conv, body); err != nil {
			return out, fmt.Errorf("write %s: %w", ConventionsRelPath, err)
		}
		out.Wrote = append(out.Wrote, ConventionsRelPath)
	}

	cfg := filepath.Join(projectDir, ConfigRelPath)
	cfgBody := []byte(defaultAiderConfig())
	prevCfg, _ := os.ReadFile(cfg)
	if !bytes.Equal(prevCfg, cfgBody) {
		if err := atomicWrite(cfg, cfgBody); err != nil {
			return out, fmt.Errorf("write %s: %w", ConfigRelPath, err)
		}
		out.Wrote = append(out.Wrote, ConfigRelPath)
	}
	return out, nil
}

// defaultAiderConfig returns the minimal .aider.conf.yml. `read:`
// loads the keystone-managed surfaces every Aider session; nothing
// else is forced — the user can layer their own config on top.
func defaultAiderConfig() string {
	return `# Generated by keystone-project. Hand-edits to keystone-managed
# keys (read) will be overwritten on the next run.
read:
  - CONVENTIONS.md
  - AGENTS.md
  - .charter/INDEX.lite.json
`
}

func ensureTrailingNewline(b []byte) []byte {
	if len(b) == 0 || b[len(b)-1] != '\n' {
		return append(b, '\n')
	}
	return b
}

func atomicWrite(destAbs string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(destAbs), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(destAbs), err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(destAbs), ".keystone-aider.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpName := tmp.Name()
	if _, err := tmp.Write(contents); err != nil {
		tmp.Close()
		os.Remove(tmpName)
		return fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpName, destAbs); err != nil {
		os.Remove(tmpName)
		return fmt.Errorf("rename %s -> %s: %w", tmpName, destAbs, err)
	}
	return nil
}
