package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestInit_FreshScaffoldGoldenFiles is a golden-file smoke test for
// `keystone init` end-to-end. Confirms that a fresh init writes the
// expected set of files into a temp dir: charter layout, project config,
// gitignore, and the agent menu file.
//
// Builds the binary once per run via `go build` (cheap on a warm build
// cache), executes it against an empty tempdir, then walks the result.
// Intentionally asserts *file presence*, not byte-equal content, so
// template improvements during 1.x don't break the regression suite —
// the template-drift check in `keystone doctor` is the right tool for
// content comparisons.
func TestInit_FreshScaffoldGoldenFiles(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping e2e init test in -short mode")
	}
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go toolchain not available")
	}

	binDir := t.TempDir()
	bin := filepath.Join(binDir, "keystone")

	// Build from the current cmd/keystone source tree. We're already inside
	// it (this test file) so the package path is "." relative to the cwd
	// the `go test` runner sets to the package directory.
	build := exec.Command("go", "build", "-o", bin, ".")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}

	projectDir := t.TempDir()
	cmd := exec.Command(bin, "init", projectDir, "--agent", "codex")
	// stdin is closed by default for exec.Cmd; non-TTY path will be taken,
	// which is what we want for a non-interactive test.
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("keystone init failed: %v\n%s", err, out)
	}

	// Files we expect to exist after a fresh init with --agent codex.
	// The list is the contract: anything important to the install ought
	// to show up here. Per-template *content* drift is not asserted —
	// keystone doctor's template-drift mode is the tool for that.
	wantFiles := []string{
		"keystone.json",
		".gitignore",
		".charter/lockfile.json",
		".charter/README.md",
		".charter/guides/README.md",
		".charter/guides/process/spec.md",
		".charter/guides/process/release.md",
		".charter/guides/process/runtime-resolution.md",
		".charter/corpus/process/runtime-resolution.md",
		".charter/corpus/README.md",
		".charter/hooks/build.md",
		".charter/hooks/lint.md",
		".charter/hooks/test.md",
		".charter/sensors/review-functional.md",
		".charter/commands/spec.md",
		".charter/commands/orient.md",
		".charter/commands/verify.md",
		".charter/commands/review.md",
		".charter/playbooks/task.md",
		".charter/adapters/codex/activation.md",
		".charter/adapters/codex/lifecycle.md",
		".charter/adapters/codex/sensors.md",
		".charter/learning/README.md",
		".charter/archive/README.md",
		".charter/skills/README.md",
		".charter/skills/keystone-bootstrap/SKILL.md",
		".charter/skills/keystone-spec/SKILL.md",
		".charter/skills/keystone-orient/SKILL.md",
		".charter/skills/keystone-check-drift/SKILL.md",
		".charter/skills/keystone-review/SKILL.md",
		".charter/skills/keystone-debt-review/SKILL.md",
		".charter/skills/keystone-mode/SKILL.md",
		".charter/skills/keystone-learn/SKILL.md",
		".charter/skills/keystone-synthesize/SKILL.md",
		".charter/skills/keystone-audit/SKILL.md",
		".charter/skills/keystone-index/SKILL.md",
		".charter/skills/keystone-verify/SKILL.md",
		".charter/skills/keystone-new-guide/SKILL.md",
		".charter/skills/keystone-new-corpus/SKILL.md",
		".charter/skills/keystone-new-sensor/SKILL.md",
		".charter/skills/keystone-new-command/SKILL.md",
		".charter/skills/keystone-new-playbook/SKILL.md",
		".charter/skills/keystone-new-adapter/SKILL.md",
		".charter/skills/keystone-new-policy/SKILL.md",
		".charter/agents/README.md",
		".charter/commands/README.md",
		".charter/corpus/state/INSTALL_PROFILE.md",
		"AGENTS.md", // codex's menu file at the project root
		// Generated by the post-install index + project step. Without
		// these the agent has no way to find the keystone skills.
		".charter/INDEX.json",
		".claude/skills/keystone-bootstrap/SKILL.md",
		".claude/skills/keystone-index/SKILL.md",
		".claude/skills/keystone-verify/SKILL.md",
		".claude/skills/keystone-new-guide/SKILL.md",
	}

	for _, rel := range wantFiles {
		path := filepath.Join(projectDir, rel)
		if info, err := os.Stat(path); err != nil {
			t.Errorf("missing expected file: %s (%v)", rel, err)
		} else if info.IsDir() {
			t.Errorf("expected file, got directory: %s", rel)
		}
	}

	// Universal-principles must NOT scaffold by default — it's opt-in
	// via --starter universal-principles.
	if _, err := os.Stat(filepath.Join(projectDir, ".charter/guides/principles/tdd.md")); !os.IsNotExist(err) {
		t.Errorf("guides/principles/tdd.md should not exist on a default init (got err = %v)", err)
	}

	// Vendored policies dir must not exist on a fresh install (no policies
	// declared yet). The .gitignore entry is created regardless so future
	// `keystone install` calls don't accidentally commit policy content.
	if _, err := os.Stat(filepath.Join(projectDir, ".charter/policies")); !os.IsNotExist(err) {
		t.Errorf("charter/policies should not exist on a fresh init with no policies declared (got err = %v)", err)
	}
}
